services:
  app:
    build: .
    container_name: demo-app
    environment:
      DD_AGENT_HOST: agent
      DD_SERVICE: demo-app
      DD_ENV: dev
      DD_VERSION: 1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - agent

  agent:
    image: "datadog/agent:7"
    container_name: dd-agent
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE:-datadoghq.com}
      DD_LOGS_ENABLED: "true"
      DD_APM_ENABLED: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_LOGS_INJECTION: "true"   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
